# Reference implementation in Python for Causal Impact.

import numpy as np
import pandas as pd
import json
import statsmodels.api as sm
import os

# Load the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/causal_impact_simulated/data"
df = pd.read_csv(f"{data_dir}/causal_impact.csv")

treatment_start = 100
n = len(df)

# Pre-treatment period: observations 1..treatment_start
pre_period = df[df['time'] <= treatment_start]
# Post-treatment period: observations (treatment_start+1)..n
post_period = df[df['time'] > treatment_start]

# Estimate counterfactual using pre-treatment trend
pre_trend = sm.OLS(pre_period['y'], sm.add_constant(pre_period['time'])).fit()

# Predict counterfactual for post-period
counterfactual = pre_trend.predict(sm.add_constant(post_period['time']))

# Point effect: actual - counterfactual
point_effects = post_period['y'].values - counterfactual
avg_effect = np.mean(point_effects)

# Cumulative effect
total_effect = np.sum(point_effects)

# CIs using standard deviation of point effects
point_effect_sd = np.std(point_effects, ddof=1)
point_effect_se = point_effect_sd / np.sqrt(len(point_effects))
avg_effect_sd = point_effect_se
avg_effect_lower = avg_effect - 1.96 * avg_effect_sd
avg_effect_upper = avg_effect + 1.96 * avg_effect_sd

cumulative_se = np.sqrt(len(point_effects)) * point_effect_sd
cumulative_lower = total_effect - 1.96 * cumulative_se
cumulative_upper = total_effect + 1.96 * cumulative_se

result = {
    'avg_effect': avg_effect,
    'avg_effect_lower': avg_effect_lower,
    'avg_effect_upper': avg_effect_upper,
    'total_effect': total_effect,
    'total_effect_lower': cumulative_lower,
    'total_effect_upper': cumulative_upper
}

out_dir = "validation/cases/causal_impact_simulated/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

# Also emit JSON on stdout so the orchestrator can avoid reading files.
print(json.dumps(result))
