# Reference implementation in Python for MICE chained equations.

import numpy as np
import pandas as pd
import json
import os

# Use the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/mice_chained_simulated/data"
df = pd.read_csv(f"{data_dir}/mice.csv")

x1 = df['x1'].to_numpy()
x2 = df['x2'].to_numpy()
x3 = df['x3'].to_numpy()
n = len(df)

# Simple reference: use mean imputation for comparison
x1_imputed = np.where(np.isnan(x1), np.nanmean(x1), x1)
x2_imputed = np.where(np.isnan(x2), np.nanmean(x2), x2)
x3_imputed = np.where(np.isnan(x3), np.nanmean(x3), x3)

# Compute pooled means and variances (reference: mean imputation)
imputed_means = [float(np.mean(x1_imputed)), float(np.mean(x2_imputed)), float(np.mean(x3_imputed))]
imputed_stds = [float(np.std(x1_imputed, ddof=1)), float(np.std(x2_imputed, ddof=1)), float(np.std(x3_imputed, ddof=1))]

result = {
    'imputed_means': imputed_means,
    'imputed_stds': imputed_stds
}

out_dir = "validation/cases/mice_chained_simulated/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

# Also emit JSON on stdout so the orchestrator can avoid reading files.
print(json.dumps(result))
