# Reference implementation in Python for Panel Heckman selection model.

import pandas as pd
import json
import statsmodels.api as sm
from scipy.stats import norm
import os

# Use the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/panel_heckman_simulated/data"
df = pd.read_csv(f"{data_dir}/panel_heckman.csv")
df['selection'] = df['selection'].astype(float)

# Simplified reference: probit selection then OLS with inverse Mills ratio.
X_sel = sm.add_constant(df[['x1', 'x2', 'x3']])
selection_model = sm.Probit(df['selection'], X_sel).fit(disp=0)
selection_coefs = selection_model.params.to_dict()

# Compute inverse Mills ratio from the linear predictor (xb = X'gamma).
xb = selection_model.fittedvalues
imr = norm.pdf(xb) / norm.cdf(xb)
df['imr'] = imr

# Estimate outcome model on selected sample, including IMR.
outcome_data = df[df['selection'] == 1].copy()
X_out = sm.add_constant(outcome_data[['x1', 'x2', 'x3', 'imr']])
outcome_model = sm.OLS(outcome_data['y'], X_out).fit()
outcome_coefs = outcome_model.params.to_dict()
# Rename the IMR coefficient for consistent comparison.
outcome_coefs['lambda_IMR'] = outcome_coefs.pop('imr')
inverse_mills_ratio = float(imr[df['selection'] == 1].mean())

result = {
    'selection_coefficients': selection_coefs,
    'outcome_coefficients': outcome_coefs,
    'inverse_mills_ratio': inverse_mills_ratio
}

out_dir = "validation/cases/panel_heckman_simulated/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

# Also emit JSON on stdout so the orchestrator can avoid reading files.
print(json.dumps(result))
