# Reference implementation in Python for Spatial Durbin model.

import pandas as pd
import json
import statsmodels.api as sm
import os

# Read the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/spatial_durbin_simulated/data"
df = pd.read_csv(f"{data_dir}/spatial_durbin.csv")

# Simplified reference: estimate OLS with spatial lags as covariates
X = sm.add_constant(df[['x1', 'x2', 'wx1', 'wx2']])
model = sm.OLS(df['y'], X).fit()

# Extract coefficients
coefs = model.params.to_dict()

result = {
    'coefficients': coefs
}

out_dir = "validation/cases/spatial_durbin_simulated/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

# Also emit JSON on stdout so the orchestrator can avoid reading files.
print(json.dumps(result))
