# Reference implementation in R for the Heckman two-step (Heckit) case.
#
# Uses a manual two-step estimator in base R because sampleSelection::heckit is
# not assumed to be installed.

# If sampleSelection is available, use it as a sanity check, but the exported
# JSON always comes from the manual implementation.

# Use the local CSV generated by the Python reference.
data_dir <- "validation/cases/heckman_mroz/data"
df <- read.csv(file.path(data_dir, "mroz.csv"))

# Variables.
sel_vars <- c("educ", "age", "kidslt6", "kidsge6", "nwifeinc")
out_vars <- c("educ", "exper", "expersq")

# First-stage probit for selection.
probit_formula <- as.formula(paste("inlf ~", paste(sel_vars, collapse = " + ")))
probit_model <- glm(probit_formula, data = df, family = binomial(link = "probit"))

# Build selection design matrix with intercept.
X_sel <- cbind(1, as.matrix(df[, sel_vars]))
z <- df$inlf

gamma <- coef(probit_model)
V_gamma <- vcov(probit_model)

# Linear index and inverse Mills ratio.
z_hat <- c(X_sel %*% gamma)
lam <- dnorm(z_hat) / pnorm(z_hat)
lam <- ifelse(z_hat < -30, -z_hat - 1 / z_hat, lam)

# δ_i = λ_i (λ_i + z_hat_i).
delta_i <- lam * (lam + z_hat)
delta_i <- ifelse(z_hat < -30, 1 + 1 / (z_hat * z_hat), delta_i)

# Second-stage OLS on selected observations.
sel <- z == 1
X_out <- cbind(1, as.matrix(df[sel, out_vars]))
y <- df[sel, "lwage"]
W <- cbind(X_out, lam[sel])

beta_delta <- solve(t(W) %*% W, t(W) %*% y)
beta <- beta_delta[1:ncol(X_out)]
delta_hat <- beta_delta[ncol(W)]

resid <- c(y - W %*% beta_delta)
ssr <- sum(resid^2)
n1 <- sum(sel)
sigma2 <- (ssr + delta_hat^2 * sum(delta_i[sel])) / n1
sigma <- sqrt(sigma2)

# Corrected covariance matrix (Heckman 1979 / Greene 2012).
Wtw_inv <- solve(t(W) %*% W)
X_sel_1 <- X_sel[sel, ]
D <- diag(delta_i[sel])
Xtd_xs <- t(W) %*% D %*% X_sel_1
correction_meat <- Xtd_xs %*% V_gamma %*% t(Xtd_xs)
correction <- Wtw_inv %*% correction_meat %*% Wtw_inv * (delta_hat^2)
vcov <- Wtw_inv * sigma2 + correction

beta_se <- sqrt(pmax(diag(vcov)[1:ncol(X_out)], 0))
delta_se <- sqrt(max(vcov[ncol(W), ncol(W)], 0))

result <- list(
  coefficients = list(
    Intercept = as.numeric(beta[1]),
    educ = as.numeric(beta[2]),
    exper = as.numeric(beta[3]),
    expersq = as.numeric(beta[4]),
    lambda_IMR = as.numeric(delta_hat)
  ),
  standard_errors = list(
    Intercept = as.numeric(beta_se[1]),
    educ = as.numeric(beta_se[2]),
    exper = as.numeric(beta_se[3]),
    expersq = as.numeric(beta_se[4]),
    lambda_IMR = as.numeric(delta_se)
  )
)

# Helper to write a compact JSON object.
json_scalar <- function(x) {
  format(as.numeric(x), digits = 16, scientific = FALSE, trim = TRUE)
}

json_named <- function(x) {
  paste0(
    "{\n    ",
    paste(
      paste0('"', names(x), '": ', json_scalar(x)),
      collapse = ",\n    "
    ),
    "\n  }"
  )
}

json_out <- paste0(
  "{\n  \"coefficients\": ",
  json_named(result$coefficients),
  ",\n  \"standard_errors\": ",
  json_named(result$standard_errors),
  "\n}\n"
)

out_dir <- "validation/cases/heckman_mroz/reference"
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

writeLines(json_out, file.path(out_dir, "expected.json"))
cat(json_out)
