# Reference implementation for the LP-DiD quickstart validation case.
# Uses pylpdid on the panel generated by data/gen.hay.

import json
from pathlib import Path

import pandas as pd
from pylpdid import LPDID

VALIDATION_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = VALIDATION_DIR / "data"
REF_DIR = VALIDATION_DIR / "reference"


def main() -> None:
    df = pd.read_csv(DATA_DIR / "panel.csv")

    res = LPDID(target_estimand="vw", max_pre=5, max_post=8).fit(
        df,
        outcome="y",
        unit="id",
        time="t",
        first_treat="g",
    )

    es = res.event_study.set_index("horizon").sort_index()
    coefficients = {}
    standard_errors = {}
    for horizon, row in es.iterrows():
        key = f"h={int(horizon)}"
        coefficients[key] = float(row["estimate"])
        standard_errors[key] = float(row["se"])

    result = {
        "coefficients": coefficients,
        "standard_errors": standard_errors,
        "n_obs": int(res.n_obs),
    }

    REF_DIR.mkdir(parents=True, exist_ok=True)
    out = json.dumps(result)
    (REF_DIR / "expected.json").write_text(out)
    print(out)


if __name__ == "__main__":
    main()
