//! Conditional re-export facade for Greeners crates.

pub mod export;

#[cfg(feature = "bayesian")]
pub use greeners_bayesian::bayesian_linear;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::bayesian_sc;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::bayesian_sfa;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::bvar;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::favar;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::mfvar;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::mixed;

#[cfg(feature = "causal")]
pub use greeners_causal::causal_forest;
#[cfg(feature = "causal")]
pub use greeners_causal::causal_impact;
#[cfg(feature = "causal")]
pub use greeners_causal::conformal;
#[cfg(feature = "causal")]
pub use greeners_causal::cuped;
#[cfg(feature = "causal")]
pub use greeners_causal::did;
#[cfg(feature = "causal")]
pub use greeners_causal::dml_crossfit;
#[cfg(feature = "causal")]
pub use greeners_causal::double_ml;
#[cfg(feature = "causal")]
pub use greeners_causal::dr_learner;
#[cfg(feature = "causal")]
pub use greeners_causal::lp_did;
#[cfg(feature = "causal")]
pub use greeners_causal::psm;
#[cfg(feature = "causal")]
pub use greeners_causal::rd;
#[cfg(feature = "causal")]
pub use greeners_causal::synth;
#[cfg(feature = "causal")]
pub use greeners_causal::synth_did;
#[cfg(feature = "causal")]
pub use greeners_causal::tmle;

pub use greeners_core::biplot;
pub use greeners_core::bootstrap;
pub use greeners_core::bspline;
pub use greeners_core::column;
pub use greeners_core::copula;
pub use greeners_core::dataframe;
pub use greeners_core::datasets;
pub use greeners_core::descrstatsw;
pub use greeners_core::distributions;
pub use greeners_core::error;
pub use greeners_core::formula;
pub use greeners_core::functional_coef;
pub use greeners_core::gmm_clustering;
pub use greeners_core::isotonic;
pub use greeners_core::linalg;
pub use greeners_core::margins;
pub use greeners_core::moment_helpers;
pub use greeners_core::multipletests;
pub use greeners_core::multivariate;
pub use greeners_core::nonparametric;
pub use greeners_core::predicate;
pub use greeners_core::proportion;
pub use greeners_core::stats;
pub use greeners_core::summary_col;
pub use greeners_core::transforms;
pub use greeners_core::types;

#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::binary_diagnostics;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::diagnostics;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::fama_macbeth;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::influence;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::model_selection;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::specification_tests;

#[cfg(feature = "glm")]
pub use greeners_glm::beta_model;
#[cfg(feature = "glm")]
pub use greeners_glm::conditional;
#[cfg(feature = "glm")]
pub use greeners_glm::discrete;
#[cfg(feature = "glm")]
pub use greeners_glm::gee;
#[cfg(feature = "glm")]
pub use greeners_glm::glm;
#[cfg(feature = "glm")]
pub use greeners_glm::glmgam;
#[cfg(feature = "glm")]
pub use greeners_glm::mnlogit;
#[cfg(feature = "glm")]
pub use greeners_glm::negbin;
#[cfg(feature = "glm")]
pub use greeners_glm::ordered;
#[cfg(feature = "glm")]
pub use greeners_glm::poisson;
#[cfg(feature = "glm")]
pub use greeners_glm::zero_inflated;

#[cfg(feature = "imputation")]
pub use greeners_imputation::imputation;
#[cfg(feature = "imputation")]
pub use greeners_imputation::mice;

#[cfg(feature = "ml")]
pub use greeners_ml::bart;
#[cfg(feature = "ml")]
pub use greeners_ml::dbscan;
#[cfg(feature = "ml")]
pub use greeners_ml::gp;
#[cfg(feature = "ml")]
pub use greeners_ml::gradient_boosting;
#[cfg(feature = "ml")]
pub use greeners_ml::grf;
#[cfg(feature = "ml")]
pub use greeners_ml::hierarchical;
#[cfg(feature = "ml")]
pub use greeners_ml::kmeans;
#[cfg(feature = "ml")]
pub use greeners_ml::mlp;
#[cfg(feature = "ml")]
pub use greeners_ml::orthogonal_forest;
#[cfg(feature = "ml")]
pub use greeners_ml::qrf;
#[cfg(feature = "ml")]
pub use greeners_ml::qrf_inference;
#[cfg(feature = "ml")]
pub use greeners_ml::random_forest;
#[cfg(feature = "ml")]
pub use greeners_ml::transformer;
#[cfg(feature = "ml")]
pub use greeners_ml::tsne;
#[cfg(feature = "ml")]
pub use greeners_ml::umap;
#[cfg(feature = "ml")]
pub use greeners_ml::xgboost;

#[cfg(feature = "ols")]
pub use greeners_ols::event_study;
#[cfg(feature = "ols")]
pub use greeners_ols::fmols;
#[cfg(feature = "ols")]
pub use greeners_ols::gls;
#[cfg(feature = "ols")]
pub use greeners_ols::glsar;
#[cfg(feature = "ols")]
pub use greeners_ols::gmm;
#[cfg(feature = "ols")]
pub use greeners_ols::heckman;
#[cfg(feature = "ols")]
pub use greeners_ols::iv;
#[cfg(feature = "ols")]
pub use greeners_ols::nls;
#[cfg(feature = "ols")]
pub use greeners_ols::ols;
#[cfg(feature = "ols")]
pub use greeners_ols::quantile;
#[cfg(feature = "ols")]
pub use greeners_ols::reg_path;
#[cfg(feature = "ols")]
pub use greeners_ols::rlm;
#[cfg(feature = "ols")]
pub use greeners_ols::rolling;
#[cfg(feature = "ols")]
pub use greeners_ols::sur;
#[cfg(feature = "ols")]
pub use greeners_ols::three_sls;
#[cfg(feature = "ols")]
pub use greeners_ols::tobit;
#[cfg(feature = "ols")]
pub use greeners_ols::wls;

#[cfg(feature = "panel")]
pub use greeners_panel::dynamic_panel;
#[cfg(feature = "panel")]
pub use greeners_panel::fa_panel;
#[cfg(feature = "panel")]
pub use greeners_panel::hausman;
#[cfg(feature = "panel")]
pub use greeners_panel::panel;
#[cfg(feature = "panel")]
pub use greeners_panel::panel_heckman;
#[cfg(feature = "panel")]
pub use greeners_panel::panel_quantile;
#[cfg(feature = "panel")]
pub use greeners_panel::panel_robust;
#[cfg(feature = "panel")]
pub use greeners_panel::panel_tobit;
#[cfg(feature = "panel")]
pub use greeners_panel::panel_var;
#[cfg(feature = "panel")]
pub use greeners_panel::pstr;
#[cfg(feature = "panel")]
pub use greeners_panel::threshold;

#[cfg(feature = "spatial")]
pub use greeners_spatial::spatial;
#[cfg(feature = "spatial")]
pub use greeners_spatial::spatial_durbin;
#[cfg(feature = "spatial")]
pub use greeners_spatial::spatial_durbin_error;
#[cfg(feature = "spatial")]
pub use greeners_spatial::spatial_panel;

#[cfg(feature = "survival")]
pub use greeners_survival::survival;

#[cfg(feature = "timeseries")]
pub use greeners_timeseries::arima;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::autoreg;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::dcc_garch;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::decomposition;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::dfm;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::dynamic_factor;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::ets;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::garch;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::hawkes;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::johansen_break;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::lstm;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::markov;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::markov_autoreg;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::midas;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::ms_var;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::mstl;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::nardl;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::quantile_var;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::setar;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::spectral;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::statespace;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::stochastic_frontier;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::sv;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::svar;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::timeseries;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::tv_copula;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::tvar;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::tvp;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::tvp_var;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::unobserved_components;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::var;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::varma;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::vecm;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::wavelet;

// Curated root re-exports

#[cfg(feature = "bayesian")]
pub use greeners_bayesian::BayesMixedGLM;
#[cfg(feature = "bayesian")]
pub use greeners_bayesian::MixedLM;
#[cfg(feature = "causal")]
pub use greeners_causal::DiffInDiff;
pub use greeners_core::BSplineBasis;
pub use greeners_core::Bootstrap;
pub use greeners_core::CanCorr;
pub use greeners_core::CategoricalColumn;
pub use greeners_core::Column;
pub use greeners_core::ColumnType;
pub use greeners_core::CovarianceType;
pub use greeners_core::DataFrame;
pub use greeners_core::DataType;
pub use greeners_core::Datasets;
pub use greeners_core::DescrStatsW;
pub use greeners_core::FactorAnalysis;
pub use greeners_core::Formula;
pub use greeners_core::GreenersError;
pub use greeners_core::HypothesisTest;
pub use greeners_core::InferenceType;
pub use greeners_core::KDEMultivariate;
pub use greeners_core::KDEUnivariate;
pub use greeners_core::Kernel;
pub use greeners_core::KernelReg;
pub use greeners_core::Lowess;
pub use greeners_core::ModelSummary;
pub use greeners_core::Rotation;
pub use greeners_core::Stats;
pub use greeners_core::SummaryCol;
pub use greeners_core::TypeInferenceConfig;
pub use greeners_core::MANOVA;
pub use greeners_core::PCA;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::BinaryDiagnostics;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::CUSUMTest;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::Diagnostics;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::Influence;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::ModelSelection;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::PanelDiagnostics;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::SpecificationTests;
#[cfg(feature = "diagnostics")]
pub use greeners_diagnostics::SummaryStats;
#[cfg(feature = "glm")]
pub use greeners_glm::BetaLink;
#[cfg(feature = "glm")]
pub use greeners_glm::BetaModel;
#[cfg(feature = "glm")]
pub use greeners_glm::ConditionalLogit;
#[cfg(feature = "glm")]
pub use greeners_glm::ConditionalMNLogit;
#[cfg(feature = "glm")]
pub use greeners_glm::ConditionalPoisson;
#[cfg(feature = "glm")]
pub use greeners_glm::CorrStructure;
#[cfg(feature = "glm")]
pub use greeners_glm::Family;
#[cfg(feature = "glm")]
pub use greeners_glm::GLMGam;
#[cfg(feature = "glm")]
pub use greeners_glm::GenPoisson;
#[cfg(feature = "glm")]
pub use greeners_glm::Link;
#[cfg(feature = "glm")]
pub use greeners_glm::Logit;
#[cfg(feature = "glm")]
pub use greeners_glm::MNLogit;
#[cfg(feature = "glm")]
pub use greeners_glm::NegBin;
#[cfg(feature = "glm")]
pub use greeners_glm::NegBinP;
#[cfg(feature = "glm")]
pub use greeners_glm::NominalGEE;
#[cfg(feature = "glm")]
pub use greeners_glm::OrderedLogit;
#[cfg(feature = "glm")]
pub use greeners_glm::OrderedProbit;
#[cfg(feature = "glm")]
pub use greeners_glm::OrdinalGEE;
#[cfg(feature = "glm")]
pub use greeners_glm::Poisson;
#[cfg(feature = "glm")]
pub use greeners_glm::Probit;
#[cfg(feature = "glm")]
pub use greeners_glm::GEE;
#[cfg(feature = "glm")]
pub use greeners_glm::GLM;
#[cfg(feature = "glm")]
pub use greeners_glm::ZINB;
#[cfg(feature = "glm")]
pub use greeners_glm::ZIP;
#[cfg(feature = "imputation")]
pub use greeners_imputation::BayesGaussMI;
#[cfg(feature = "imputation")]
pub use greeners_imputation::MICE;
#[cfg(feature = "ols")]
pub use greeners_ols::Equation;
#[cfg(feature = "ols")]
pub use greeners_ols::OlsResult;
#[cfg(feature = "ols")]
pub use greeners_ols::QuantileReg;
#[cfg(feature = "ols")]
pub use greeners_ols::RecursiveLS;
#[cfg(feature = "ols")]
pub use greeners_ols::RobustNorm;
#[cfg(feature = "ols")]
pub use greeners_ols::RollingOLS;
#[cfg(feature = "ols")]
pub use greeners_ols::RollingWLS;
#[cfg(feature = "ols")]
pub use greeners_ols::SurEquation;
#[cfg(feature = "ols")]
pub use greeners_ols::ThreeSLS;
#[cfg(feature = "ols")]
pub use greeners_ols::FGLS;
#[cfg(feature = "ols")]
pub use greeners_ols::GLSAR;
#[cfg(feature = "ols")]
pub use greeners_ols::GMM;
#[cfg(feature = "ols")]
pub use greeners_ols::IV;
#[cfg(feature = "ols")]
pub use greeners_ols::OLS;
#[cfg(feature = "ols")]
pub use greeners_ols::RLM;
#[cfg(feature = "ols")]
pub use greeners_ols::SUR;
#[cfg(feature = "ols")]
pub use greeners_ols::WLS;
#[cfg(feature = "panel")]
pub use greeners_panel::ArellanoBond;
#[cfg(feature = "panel")]
pub use greeners_panel::BetweenEstimator;
#[cfg(feature = "panel")]
pub use greeners_panel::FixedEffects;
#[cfg(feature = "panel")]
pub use greeners_panel::HausmanTest;
#[cfg(feature = "panel")]
pub use greeners_panel::PanelThreshold;
#[cfg(feature = "panel")]
pub use greeners_panel::RandomEffects;
#[cfg(feature = "survival")]
pub use greeners_survival::CoxPH;
#[cfg(feature = "survival")]
pub use greeners_survival::KaplanMeier;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::state_space_estimate;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::AutoReg;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::Decomposition;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::ExponentialSmoothing;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::GarchDist;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::GarchModelType;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::KalmanFilter;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::KalmanSmoother;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::MarkovSwitching;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::SVarIdentification;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::StateSpaceModel;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::TimeSeries;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::ARDL;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::ARIMA;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::SVAR;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::VAR;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::VARMA;
#[cfg(feature = "timeseries")]
pub use greeners_timeseries::VECM;