# Reference implementation in Python for Double Machine Learning.

import pandas as pd
import json
import statsmodels.api as sm
import os

# Load the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/double_ml_simulated/data"
df = pd.read_csv(f"{data_dir}/double_ml.csv")

# Simple reference: partial out controls via OLS of y and d on X, then regress residuals.
X = sm.add_constant(df[['x1', 'x2', 'x3', 'x4', 'x5']])

y_res = sm.OLS(df['y'], X).fit().resid
d_res = sm.OLS(df['d'], X).fit().resid

fit = sm.OLS(y_res, d_res).fit()
ate_coefficient = float(fit.params.iloc[0])
ate_standard_error = float(fit.bse.iloc[0])

result = {
    'ate_coefficient': ate_coefficient,
    'ate_standard_error': ate_standard_error
}

out_dir = "validation/cases/double_ml_simulated/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

# Also emit JSON on stdout so the orchestrator can avoid reading files.
print(json.dumps(result))
