# Reference implementation in Python for robust Hausman test.

import numpy as np
import pandas as pd
import json
import os
from scipy import stats

# Load the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/hausman_robust_wooldridge_wagepan/data"
wagepan = pd.read_csv(f"{data_dir}/wagepan.csv")

y = wagepan['lwage'].values.astype(float)
X = wagepan[['exper', 'expersq', 'married', 'union']].values.astype(float)
entity = wagepan['nr'].values

# Add constant for RE estimation.
X_const = np.column_stack([np.ones(X.shape[0]), X])
entity_ids, entity_inv = np.unique(entity, return_inverse=True)
n = len(y)
T_i = np.bincount(entity_inv)

def _ols(X, y):
    return np.linalg.lstsq(X, y, rcond=None)[0]

def _se_from_ols(X, y, beta, df):
    resid = y - X @ beta
    sigma2 = np.sum(resid ** 2) / df
    xtx_inv = np.linalg.inv(X.T @ X + 1e-12 * np.eye(X.shape[1]))
    vcov = sigma2 * xtx_inv
    return np.sqrt(np.maximum(np.diag(vcov), 0.0))

# Within (FE) estimation: demean within each entity and estimate slopes.
def _within_estimate(X, y, entity_inv):
    means_X = np.zeros((len(np.unique(entity_inv)), X.shape[1]))
    for j in range(X.shape[1]):
        means_X[:, j] = np.bincount(entity_inv, weights=X[:, j]) / T_i
    means_y = np.bincount(entity_inv, weights=y) / T_i
    X_dm = X - means_X[entity_inv]
    y_dm = y - means_y[entity_inv]
    beta = _ols(X_dm, y_dm)
    # Correct degrees of freedom: n - k - (G - 1)
    df = max(1, n - X.shape[1] - len(np.unique(entity_inv)) + 1)
    se = _se_from_ols(X_dm, y_dm, beta, df)
    return beta, se

# Random effects estimation via quasi-demeaning (Swamy-Arora / GLS).
def _re_estimate(X, y, entity_inv):
    beta_fe, _ = _within_estimate(X, y, entity_inv)
    resid_fe = y - X @ beta_fe
    mean_resid = np.bincount(entity_inv, weights=resid_fe) / T_i
    resid_dm = resid_fe - mean_resid[entity_inv]
    df_w = max(1, n - len(entity_ids) - X.shape[1])
    sigma2_nu = np.sum(resid_dm ** 2) / df_w

    entity_mean_X = np.zeros((len(entity_ids), X.shape[1]))
    for j in range(X.shape[1]):
        entity_mean_X[:, j] = np.bincount(entity_inv, weights=X[:, j]) / T_i
    entity_mean_y = np.bincount(entity_inv, weights=y) / T_i
    beta_between = _ols(entity_mean_X, entity_mean_y)
    resid_between = entity_mean_y - entity_mean_X @ beta_between
    df_b = max(1, len(entity_ids) - X.shape[1])
    sigma2_v = np.sum(resid_between ** 2) / df_b
    mean_T = T_i.mean()
    sigma2_alpha = max(1e-12, sigma2_v - sigma2_nu / mean_T)

    theta = 1.0 - np.sqrt(sigma2_nu / (sigma2_nu + T_i * sigma2_alpha))
    X_transformed = X.copy()
    y_transformed = y.copy()
    for i in range(len(entity_ids)):
        mask = entity_inv == i
        X_transformed[mask] -= theta[i] * entity_mean_X[i]
        y_transformed[mask] -= theta[i] * entity_mean_y[i]
    beta_re = _ols(X_transformed, y_transformed)
    df = max(1, n - X.shape[1])
    se = _se_from_ols(X_transformed, y_transformed, beta_re, df)
    return beta_re, se

beta_fe, se_fe = _within_estimate(X_const, y, entity_inv)
beta_re, se_re = _re_estimate(X_const, y, entity_inv)

# Common coefficients: slopes only (index 1..4), excluding RE constant.
fe_idx = [1, 2, 3, 4]
re_idx = [1, 2, 3, 4]

beta_fe_aligned = beta_fe[fe_idx]
beta_re_aligned = beta_re[re_idx]
se_fe_aligned = se_fe[fe_idx]
se_re_aligned = se_re[re_idx]

diff = beta_fe_aligned - beta_re_aligned
var_diff = se_fe_aligned ** 2 - se_re_aligned ** 2
# Diagonal Hausman statistic, excluding negative variances.
positive = var_diff > 0
chi2 = float(np.sum((diff[positive] ** 2) / var_diff[positive]))
df = int(positive.sum())
p_value = float(1 - stats.chi2.cdf(chi2, df))

result = {
    'test_statistic': chi2,
    'p_value': p_value,
    'degrees_of_freedom': df
}

out_dir = "validation/cases/hausman_robust_wooldridge_wagepan/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

print(json.dumps(result))
