pub mod dsv;
#[cfg(feature = "native")]
pub mod dta;
pub mod excel;
#[cfg(feature = "native")]
pub mod fetch;
#[cfg(feature = "odbc")]
pub mod odbc;
#[cfg(feature = "native")]
pub mod packages;
pub mod parquet;
pub mod plot;
#[cfg(feature = "native")]
pub mod sqlite;
