# Reference implementation in Python for K-Means clustering.

import numpy as np
import pandas as pd
import json
import os

# Use the CSV generated by the R reference so both references agree.
data_dir = "validation/cases/kmeans_simulated/data"
df = pd.read_csv(f"{data_dir}/kmeans.csv")

# Simple k-means implementation (Lloyd's algorithm) with deterministic seed.
data = df.values.astype(float)

def _kmeans(data, k=3, max_iter=100, seed=42):
    rng = np.random.default_rng(seed)
    n, d = data.shape
    # k-means++ initialization
    centroids = np.zeros((k, d))
    centroids[0] = data[rng.integers(n)]
    for i in range(1, k):
        dists = np.array([min(np.linalg.norm(data[j] - centroids[c]) for c in range(i)) for j in range(n)])
        probs = dists / dists.sum()
        centroids[i] = data[rng.choice(n, p=probs)]
    for _ in range(max_iter):
        labels = np.argmin(np.linalg.norm(data[:, None, :] - centroids, axis=2), axis=1)
        new_centroids = np.array([data[labels == c].mean(axis=0) if np.any(labels == c) else centroids[c] for c in range(k)])
        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    labels = np.argmin(np.linalg.norm(data[:, None, :] - centroids, axis=2), axis=1)
    inertia = float(np.sum((data - centroids[labels]) ** 2))
    return centroids, labels, inertia

centroids, labels, inertia = _kmeans(data, k=3, max_iter=100, seed=42)

# Compute sum-of-squares statistics.
total_ss = float(np.sum((data - data.mean(axis=0)) ** 2))
between_ss = 0.0
for c in range(3):
    cluster_mask = labels == c
    between_ss += float(np.sum(cluster_mask) * np.sum((centroids[c] - data.mean(axis=0)) ** 2))
pct_explained = 100 * (1 - inertia / total_ss) if total_ss > 0 else 0.0

# Order centroids by the first coordinate so comparison is deterministic.
ordered_centroids = centroids[np.argsort(centroids[:, 0])]
result = {
    'inertia': inertia,
    'between_ss': between_ss,
    'total_ss': total_ss,
    'pct_explained': pct_explained,
    'cluster_centers': ordered_centroids.flatten().tolist()
}

out_dir = "validation/cases/kmeans_simulated/reference"
os.makedirs(out_dir, exist_ok=True)

with open(f"{out_dir}/expected.json", 'w') as f:
    json.dump(result, f, indent=2)

# Also emit JSON on stdout so the orchestrator can avoid reading files.
print(json.dumps(result))
